<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka.Cluster.Hosting" Version="1.5.69" />
    <PackageReference Include="Npgsql" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="PostgreSql\Migrations\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hive.Domain\Hive.Domain.csproj" />
    <ProjectReference Include="..\Hive.Infrastructure\Hive.Infrastructure.csproj" />
  </ItemGroup>

</Project>
